/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipotela;

/**
 *
 * @author tls15
 */
public class ListarDependencias extends javax.swing.JFrame {

    /**
     * Creates new form ListarDependencias
     */
    public ListarDependencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblimagem = new javax.swing.JLabel();
        BotaoExcluirDep = new javax.swing.JButton();
        PainelTabelaDep = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaResultado = new javax.swing.JTable();
        BotaoNovoDep = new javax.swing.JButton();
        BotaoEditarDep = new javax.swing.JButton();
        PainelFiltroPatrocinador = new javax.swing.JPanel();
        lblNomePatrocinador = new javax.swing.JLabel();
        CampoNomePesquisaDep = new javax.swing.JTextField();
        BotaoLimparDep = new javax.swing.JButton();
        BotaoBuscarDep = new javax.swing.JButton();
        BotaoSairDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/img/stadium-29484.jpg"))); // NOI18N

        BotaoExcluirDep.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoExcluirDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/delete.png"))); // NOI18N
        BotaoExcluirDep.setText("Excluir");
        BotaoExcluirDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirDepActionPerformed(evt);
            }
        });

        PainelTabelaDep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        TabelaResultado.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        TabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Capacidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaResultado);

        javax.swing.GroupLayout PainelTabelaDepLayout = new javax.swing.GroupLayout(PainelTabelaDep);
        PainelTabelaDep.setLayout(PainelTabelaDepLayout);
        PainelTabelaDepLayout.setHorizontalGroup(
            PainelTabelaDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaDepLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        PainelTabelaDepLayout.setVerticalGroup(
            PainelTabelaDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaDepLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        BotaoNovoDep.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoNovoDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/Novo.png"))); // NOI18N
        BotaoNovoDep.setText("Novo");
        BotaoNovoDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoDepActionPerformed(evt);
            }
        });

        BotaoEditarDep.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoEditarDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/edit.png"))); // NOI18N
        BotaoEditarDep.setText("Editar");
        BotaoEditarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarDepActionPerformed(evt);
            }
        });

        PainelFiltroPatrocinador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Dependencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        lblNomePatrocinador.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblNomePatrocinador.setText("Nome");

        BotaoLimparDep.setBackground(new java.awt.Color(255, 255, 255));
        BotaoLimparDep.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoLimparDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/limpar.png"))); // NOI18N
        BotaoLimparDep.setText("Limpar");
        BotaoLimparDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparDepActionPerformed(evt);
            }
        });

        BotaoBuscarDep.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoBuscarDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1474448538_magnifyingglass.png"))); // NOI18N
        BotaoBuscarDep.setText("Buscar");

        BotaoSairDep.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BotaoSairDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1473722394_No.png"))); // NOI18N
        BotaoSairDep.setText("Sair");
        BotaoSairDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFiltroPatrocinadorLayout = new javax.swing.GroupLayout(PainelFiltroPatrocinador);
        PainelFiltroPatrocinador.setLayout(PainelFiltroPatrocinadorLayout);
        PainelFiltroPatrocinadorLayout.setHorizontalGroup(
            PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                .addGroup(PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblNomePatrocinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoNomePesquisaDep, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BotaoLimparDep)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoBuscarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoSairDep, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PainelFiltroPatrocinadorLayout.setVerticalGroup(
            PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomePesquisaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomePatrocinador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLimparDep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSairDep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelFiltroPatrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BotaoNovoDep, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoEditarDep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoExcluirDep))
                            .addComponent(PainelTabelaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelFiltroPatrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelTabelaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoEditarDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoExcluirDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoNovoDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoExcluirDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoExcluirDepActionPerformed

    private void BotaoNovoDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoDepActionPerformed
        TelaCadastroDependencias abrir = new TelaCadastroDependencias();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_BotaoNovoDepActionPerformed

    private void BotaoEditarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEditarDepActionPerformed

    private void BotaoLimparDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimparDepActionPerformed

    private void BotaoSairDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairDepActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoSairDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarDependencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscarDep;
    private javax.swing.JButton BotaoEditarDep;
    private javax.swing.JButton BotaoExcluirDep;
    private javax.swing.JButton BotaoLimparDep;
    private javax.swing.JButton BotaoNovoDep;
    private javax.swing.JButton BotaoSairDep;
    private javax.swing.JTextField CampoNomePesquisaDep;
    private javax.swing.JPanel PainelFiltroPatrocinador;
    private javax.swing.JPanel PainelTabelaDep;
    private javax.swing.JTable TabelaResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomePatrocinador;
    private javax.swing.JLabel lblimagem;
    // End of variables declaration//GEN-END:variables
}
