/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipotela;

import br.edu.ifnmg.MasterClub.Entidades.Patrocinio;
import br.edu.ifnmg.MasterClub.Entidades.PatrocinioRepositorio;
import br.edu.ifnmg.MasterClub.Persistencia.ConnectionFactory;
import br.edu.ifnmg.MasterClub.Persistencia.DB;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tls15
 */
public class ListarPatrocinadores extends javax.swing.JFrame {
    PatrocinioRepositorio bd_dao;
    Patrocinio patrocinador = new Patrocinio();
    ArrayList<Patrocinio> efetuarBusca = new ArrayList<>();
    protected Connection conn;
    /**
     * Creates new form ListarPatrocinadores
     */
   public ListarPatrocinadores() {
        try {
            DB.Iniciar();
            conn = ConnectionFactory.getConnection();
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver não encontrado!");
        
        } catch (Exception ex) {
            System.out.println(ex);
        }
        initComponents();
        this.bd_dao = GerenciarFuncionamento.getPatrocinio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFiltroPatrocinador = new javax.swing.JPanel();
        lblNomePatrocinador = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        BotaoLimparPat = new javax.swing.JButton();
        BotaoBuscarPat = new javax.swing.JButton();
        BotaoSairPat = new javax.swing.JButton();
        BotaoExcluirPat = new javax.swing.JButton();
        PainelTabelaPat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        BotaoNovoPat = new javax.swing.JButton();
        BotaoEditarPat = new javax.swing.JButton();
        lblimagem = new javax.swing.JLabel();
        btnMostrarTodos = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PainelFiltroPatrocinador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Patrocinadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        lblNomePatrocinador.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblNomePatrocinador.setText("Nome");

        BotaoLimparPat.setBackground(new java.awt.Color(255, 255, 255));
        BotaoLimparPat.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoLimparPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/limpar.png"))); // NOI18N
        BotaoLimparPat.setText("Limpar");
        BotaoLimparPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparPatActionPerformed(evt);
            }
        });

        BotaoBuscarPat.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoBuscarPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1474448538_magnifyingglass.png"))); // NOI18N
        BotaoBuscarPat.setText("Buscar");
        BotaoBuscarPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscarPatActionPerformed(evt);
            }
        });

        BotaoSairPat.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BotaoSairPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1473722394_No.png"))); // NOI18N
        BotaoSairPat.setText("Sair");
        BotaoSairPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairPatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFiltroPatrocinadorLayout = new javax.swing.GroupLayout(PainelFiltroPatrocinador);
        PainelFiltroPatrocinador.setLayout(PainelFiltroPatrocinadorLayout);
        PainelFiltroPatrocinadorLayout.setHorizontalGroup(
            PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                .addGroup(PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblNomePatrocinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BotaoLimparPat)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoBuscarPat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoSairPat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PainelFiltroPatrocinadorLayout.setVerticalGroup(
            PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFiltroPatrocinadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomePatrocinador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(PainelFiltroPatrocinadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLimparPat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscarPat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSairPat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        BotaoExcluirPat.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoExcluirPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/delete.png"))); // NOI18N
        BotaoExcluirPat.setText("Excluir");
        BotaoExcluirPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirPatActionPerformed(evt);
            }
        });

        PainelTabelaPat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        tblResultado.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResultado);

        javax.swing.GroupLayout PainelTabelaPatLayout = new javax.swing.GroupLayout(PainelTabelaPat);
        PainelTabelaPat.setLayout(PainelTabelaPatLayout);
        PainelTabelaPatLayout.setHorizontalGroup(
            PainelTabelaPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaPatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        PainelTabelaPatLayout.setVerticalGroup(
            PainelTabelaPatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaPatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        BotaoNovoPat.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoNovoPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/Novo.png"))); // NOI18N
        BotaoNovoPat.setText("Novo");
        BotaoNovoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoPatActionPerformed(evt);
            }
        });

        BotaoEditarPat.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoEditarPat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/edit.png"))); // NOI18N
        BotaoEditarPat.setText("Editar");
        BotaoEditarPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarPatActionPerformed(evt);
            }
        });

        lblimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/img/item_heineken.png"))); // NOI18N

        btnMostrarTodos.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        btnMostrarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1474448538_magnifyingglass.png"))); // NOI18N
        btnMostrarTodos.setText("Buscar");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1474489777_pdf.png"))); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelFiltroPatrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelTabelaPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoNovoPat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoEditarPat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoExcluirPat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRelatorio)))
                        .addGap(10, 10, 10)
                        .addComponent(lblimagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelFiltroPatrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTabelaPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoEditarPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoExcluirPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoNovoPat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLimparPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimparPatActionPerformed

    private void BotaoSairPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairPatActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoSairPatActionPerformed

    private void BotaoExcluirPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirPatActionPerformed
        int posicaoVetor = tblResultado.getSelectedRow();
        
        if(posicaoVetor >=0){
            Patrocinio patrocinio = efetuarBusca.get(posicaoVetor);
            String mensagem = "Deseja realmente excluir esse patrcinador?";
            int opcao = JOptionPane.showConfirmDialog(this, mensagem, "Mensagem de confirmação", JOptionPane.YES_NO_OPTION);
           
            if(opcao == JOptionPane.YES_OPTION){
                bd_dao.Apagar(patrocinio);
                buscarTodos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Escolha o campo a ser excluído!");
        }
    }//GEN-LAST:event_BotaoExcluirPatActionPerformed

    private void BotaoNovoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoPatActionPerformed
        TelaCadastroPatrocinador abrir = new TelaCadastroPatrocinador();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_BotaoNovoPatActionPerformed

    private void BotaoEditarPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarPatActionPerformed
        int posicao = tblResultado.getSelectedRow();
        
        if(posicao >= 0){
            Patrocinio patrocinio = efetuarBusca.get(posicao);
            String mensagem = "Quase pronto, deseja editar esta dependencia?";
            int opcao = JOptionPane.showConfirmDialog(this, mensagem, "Mensagem de Confirmação", JOptionPane.YES_NO_OPTION);
            
            if(opcao == JOptionPane.YES_OPTION ){
                TelaCadastroPatrocinador telaCadastrarPatrocinador = new TelaCadastroPatrocinador(patrocinio,this);
                telaCadastrarPatrocinador.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Escolha o campo na tabela a ser modificado");
            }
            
        }
    }//GEN-LAST:event_BotaoEditarPatActionPerformed

    private void BotaoBuscarPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscarPatActionPerformed
        buscar(txtNome.getText());
    }//GEN-LAST:event_BotaoBuscarPatActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        buscarTodos();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        try {
        PreparedStatement sql = conn.prepareStatement("select id, nome, valor from patrocinio");
        ResultSet resultado = sql.executeQuery();
        JRResultSetDataSource relaResul = new JRResultSetDataSource(resultado);
        String reportDefinition = "RelatorioPatrocinadores.jasper";

        InputStream reportDefinitionStream = getClass().getResourceAsStream(reportDefinition);
        JasperPrint jpPrint = JasperFillManager.fillReport(reportDefinitionStream, new HashMap(), relaResul);
        JasperViewer jv = new JasperViewer(jpPrint);
        jv.setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(ListarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JRException ex) {
        Logger.getLogger(ListarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPatrocinadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscarPat;
    private javax.swing.JButton BotaoEditarPat;
    private javax.swing.JButton BotaoExcluirPat;
    private javax.swing.JButton BotaoLimparPat;
    private javax.swing.JButton BotaoNovoPat;
    private javax.swing.JButton BotaoSairPat;
    private javax.swing.JPanel PainelFiltroPatrocinador;
    private javax.swing.JPanel PainelTabelaPat;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomePatrocinador;
    private javax.swing.JLabel lblimagem;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        txtNome.setText("");        
    }

    private void buscarTodos() {
        
        Patrocinio filtro = new Patrocinio(0,null,null);
        efetuarBusca =(ArrayList<Patrocinio>) bd_dao.Buscar(filtro);
        preenchimentodaTabela(efetuarBusca);
        
    }

    private void buscar(String nome) {
        
        Patrocinio filtro = new Patrocinio(0,nome,null);
        efetuarBusca = (ArrayList<Patrocinio>) bd_dao.Buscar(filtro);
        preenchimentodaTabela(efetuarBusca);
        
    }
    private void preenchimentodaTabela(ArrayList<Patrocinio> efetuarBusca) {
        
        DefaultTableModel coluna = new DefaultTableModel();
        
        coluna.addColumn("id");
        coluna.addColumn("nome");
        coluna.addColumn("Valor");
             
        for(Patrocinio BP:efetuarBusca){
            Vector linha = new Vector();
            linha.add(BP.getId());
            linha.add(BP.getNome());
            linha.add(BP.getValorPatrocinio());            
            
            coluna.addRow(linha);
            
        }
        
        tblResultado.setModel(coluna);
    }
}
