/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipotela;

/**
 *
 * @author tls15
 */
public class ListarJogadores extends javax.swing.JFrame {

    /**
     * Creates new form ListarJogadores
     */
    public ListarJogadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFiltroJogadores = new javax.swing.JPanel();
        lblNomeJogador = new javax.swing.JLabel();
        CampoNomePesquisaJogador = new javax.swing.JTextField();
        BotaoLimparJogador = new javax.swing.JButton();
        BotaoBuscarJogador = new javax.swing.JButton();
        lblimagem = new javax.swing.JLabel();
        BotaoSairJogador = new javax.swing.JButton();
        BotaoNovoJogador = new javax.swing.JButton();
        BotaoEditarJogador = new javax.swing.JButton();
        BotaoExcluirJogador = new javax.swing.JButton();
        PainelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelFiltroJogadores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Jogadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        lblNomeJogador.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblNomeJogador.setText("Nome");

        BotaoLimparJogador.setBackground(new java.awt.Color(255, 255, 255));
        BotaoLimparJogador.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoLimparJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/limpar.png"))); // NOI18N
        BotaoLimparJogador.setText("Limpar");
        BotaoLimparJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparJogadorActionPerformed(evt);
            }
        });

        BotaoBuscarJogador.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoBuscarJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1474448538_magnifyingglass.png"))); // NOI18N
        BotaoBuscarJogador.setText("Buscar");

        lblimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/img/1487815044_Notes.png"))); // NOI18N

        BotaoSairJogador.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        BotaoSairJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/1473722394_No.png"))); // NOI18N
        BotaoSairJogador.setText("Sair");
        BotaoSairJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairJogadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFiltroJogadoresLayout = new javax.swing.GroupLayout(PainelFiltroJogadores);
        PainelFiltroJogadores.setLayout(PainelFiltroJogadoresLayout);
        PainelFiltroJogadoresLayout.setHorizontalGroup(
            PainelFiltroJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFiltroJogadoresLayout.createSequentialGroup()
                .addGroup(PainelFiltroJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFiltroJogadoresLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblNomeJogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoNomePesquisaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelFiltroJogadoresLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BotaoLimparJogador)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoBuscarJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoSairJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(lblimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        PainelFiltroJogadoresLayout.setVerticalGroup(
            PainelFiltroJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFiltroJogadoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PainelFiltroJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomePesquisaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(PainelFiltroJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLimparJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscarJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSairJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(PainelFiltroJogadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotaoNovoJogador.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoNovoJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/Novo.png"))); // NOI18N
        BotaoNovoJogador.setText("Novo");
        BotaoNovoJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoJogadorActionPerformed(evt);
            }
        });

        BotaoEditarJogador.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoEditarJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/edit.png"))); // NOI18N
        BotaoEditarJogador.setText("Editar");
        BotaoEditarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarJogadorActionPerformed(evt);
            }
        });

        BotaoExcluirJogador.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        BotaoExcluirJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prototipotela/icone/delete.png"))); // NOI18N
        BotaoExcluirJogador.setText("Excluir");
        BotaoExcluirJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirJogadorActionPerformed(evt);
            }
        });

        PainelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N

        TabelaResultado.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        TabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Posição", "Lado", "Categoria", "Naturalidade", "Idade", "Altura", "Peso", "CPF", "RG", "Clube"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaResultado);

        javax.swing.GroupLayout PainelTabelaLayout = new javax.swing.GroupLayout(PainelTabela);
        PainelTabela.setLayout(PainelTabelaLayout);
        PainelTabelaLayout.setHorizontalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        PainelTabelaLayout.setVerticalGroup(
            PainelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelFiltroJogadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(BotaoNovoJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoEditarJogador)
                .addGap(26, 26, 26)
                .addComponent(BotaoExcluirJogador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelFiltroJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoEditarJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoNovoJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoExcluirJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairJogadorActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoSairJogadorActionPerformed

    private void BotaoNovoJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoJogadorActionPerformed
        TelaCadastroJogadores abrir = new TelaCadastroJogadores();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoNovoJogadorActionPerformed

    private void BotaoEditarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEditarJogadorActionPerformed

    private void BotaoExcluirJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoExcluirJogadorActionPerformed

    private void BotaoLimparJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimparJogadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarJogadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscarJogador;
    private javax.swing.JButton BotaoEditarJogador;
    private javax.swing.JButton BotaoExcluirJogador;
    private javax.swing.JButton BotaoLimparJogador;
    private javax.swing.JButton BotaoNovoJogador;
    private javax.swing.JButton BotaoSairJogador;
    private javax.swing.JTextField CampoNomePesquisaJogador;
    private javax.swing.JPanel PainelFiltroJogadores;
    private javax.swing.JPanel PainelTabela;
    private javax.swing.JTable TabelaResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeJogador;
    private javax.swing.JLabel lblimagem;
    // End of variables declaration//GEN-END:variables
}
